spring.application.name=StudentManagement
spring.datasource.url=jdbc:mysql://localhost:3306/StudentManagement
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.configuration.map-underscore-to-camel-case=true
# UTF-8 \u6587\u5B57\u5316\u3051\u9632\u6B62\u8A2D\u5B9A\uFF08Spring Boot \u73FE\u884C\u63A8\u5968\u5F62\u5F0F\uFF09
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
spring.messages.encoding=UTF-8
# \u958B\u767A\u4E2D\u306E\u307F\u3002\u5B8C\u6210\u5F8C\u524A\u9664
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl