spring.application.name=StudentManagement
spring.datasource.url=jdbc:mysql://localhost:3306/StudentManagement
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# UTF-8 \u6587\u5B57\u5316\u3051\u9632\u6B62\u8A2D\u5B9A\uFF08Spring Boot \u73FE\u884C\u63A8\u5968\u5F62\u5F0F\uFF09
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
spring.messages.encoding=UTF-8
#MyBatis\u306E\u8A2D\u5B9A
# \u30B9\u30CD\u30FC\u30AF\u30B1\u30FC\u30B9 \u2192 \u30AD\u30E3\u30E1\u30EB\u30B1\u30FC\u30B9\u81EA\u52D5\u5909\u63DB
mybatis.configuration.map-underscore-to-camel-case=true
# MapperXML\u306E\u5834\u6240\u6307\u5B9A
mybatis.mapper-locations=classpath:mapper/*.xml
# \u30AF\u30E9\u30B9\u540D\u3092\u77ED\u7E2E\u540D\u3067\u4F7F\u3048\u308B\u3088\u3046\u306B\u3059\u308B\u3002
mybatis.type-aliases-package=reisetech.studentmanagement.date

